#!/bin/sh
# A script to build SixTrack with ifort (Lahey ?)
echo "Trying to build SixTrack SixTrack_4518_cernlib_crlibm_ifort_O"
cd crlibm
make clean
make
cp *.o ..
cd ..
./compile_fortran.bat
./link_intel.bat
